name: CI using React Template
on:
  workflow_dispatch:
permissions:
  packages: write
jobs:
  React-CI:
    uses: nadametwaly/Reusable_workflows-github-actions/.github/workflows/React-CI-Template.yml@main
    with:
      node-version: '20'
      lint_phase: true
      unit_test: true
      docker_registry: ghcr.io
      docker_image_name: react-app-cicd
      docker_image_tag: latest
      
      Docker_Username: ${{ github.actor }}
    secrets:
      docker_password: ${{ secrets.GITHUB_TOKEN }} 