name: CI using React Template
on:
  workflow_dispatch:
permissions:
  packages: write
jobs:
  React-CI:
    uses: nadametwaly/Reusable_workflows-github-actions/.github/workflows/CI-using-React-template.yml@main
      with:
        node_version: '20'
        docker_image_name: React-App-CICD
    secrets:
      docker_password: ${{ secrets.GITHUB_TOKEN }}