name: Job Outputs
on:
    workflow_dispatch:
jobs:
    generate-message:
        runs-on: ubuntu-latest
        outputs:
            job_message: ${{ steps.set-message.outputs.message }}
        steps:
          - name: Generate message
            id: set-message
            run: |
                echo "message=Hello from Job 1!" >> $GITHUB_OUTPUT
                echo "Job 1 step output: Hello from Job 1!"
    consume-message:
        runs-on: ubuntu-latest
        needs: generate-message
        steps:
          - name: Print message from previous job
            run: |
                echo "Job 2 received message: ${{ needs.generate-message.outputs.job_message }}"

