name: Service Containers Practice
on: 
    push:
    workflow_dispatch:
permissions:
  packages: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
        image: alpine:latest
    services:   #Default container port 80 is already exposed internally
      nginx:
        image: nginx:alpine

      apache:
        image: httpd:2.4

    steps:
      - name: install curl
        run: apk add --no-cache curl
      - name: Check NGINX Service
        run: |
          echo "Checking NGINX service..."
          curl -f http://nginx

      - name: Check Apache Service
        run: |
          echo "Checking Apache service..."
          curl -f http://apache